language: julia
os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls Pkg.test("ClinicalTrialUtilities"; coverage = true);
  - julia -e 'using Pkg; cd(Pkg.dir("ClinicalTrialUtilities")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("ClinicalTrialUtilities")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - os:
        - windows
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
